version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=bikedb
    ports:
      - 5433:5432
#    volumes:
#      - ./contrib/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
#      - ./pgdata:/var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
